
name: CI coverage

on:
  push:
    branches: ["main"]
    paths:
    - ".github/workflows/ci-coverage.yml"
    - "pyproject.toml"
    - "src/**/*.py"
    - "src/**/*.pyx"
    - "src/**/*.pxd"
    - "tests/**/*.py"
  pull_request:
    branches: ["main"]

jobs:
  build-and-run-test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
        sudo apt-get install -y mesa-utils xvfb libfontconfig1 ttf-mscorefonts-installer
        python -m pip install --upgrade pip setuptools
        python -m pip install cython coverage pytest pytest-xvfb
    - name: Build in place with coverage analysis enabled
      run: |
        pip3 install .
      env:
        FLITTER_BUILD_COVERAGE: 1
    - name: Run tests with coverage
      id: coverage
      run: |
        coverage run -m pytest
        echo "percent=`coverage report | grep '^TOTAL' | cut -c60-70`" >> "${GITHUB_OUTPUT}"
    - name: Generate HTML coverage report
      run: |
        coverage html
    - name: Generate coverage badge
      uses: emibcn/badge-action@v2.0.3
      with:
        label: 'CI coverage'
        label-color: '333'
        status: ${{ steps.coverage.outputs.percent }}
        color: 'blue'
        path: htmlcov/badge.svg
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: htmlcov
        path: htmlcov/
    - name: Update badge gist
      uses: stellarhub/push-gist-action@v1
      with:
        token: ${{ secrets.GIST }}
        gist_id: b7237d8b4e7ff50c3f284cb939e949d0
        file_path: htmlcov/badge.svg
