
name: Release package

on:
  release:
    types: [published]

jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build package
      run: |
        python -m build --sdist
    - name: Store the distribution
      uses: actions/upload-artifact@v4
      with:
        name: python-sdist
        path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, macos-15, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23.3
    - uses: actions/upload-artifact@v4
      with:
        name: python-wheel-${{ matrix.os }}-${{ strategy.job-index }}
        path: wheelhouse/*.whl

  publish-to-pypi:
    name: Publish package to PyPI
    needs:
    - build_sdist
    - build_wheels
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/flitter-lang
    permissions:
      id-token: write
    steps:
    - name: Retrieve the distribution
      uses: actions/download-artifact@v4
      with:
        pattern: python-*
        path: dist/
        merge-multiple: true
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
